config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :microposts do
    member do
      post :retweet
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  validates :age , numericality: { greater_than: 0, less_than: 150 } 
  validates :region , length: { minimum: 0, maximum: 10 } 
  validates :profile , length: { minimum: 0, maximum: 500 } 
  
  has_many :microposts
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  has_many :favorites, foreign_key: 'user_id', dependent: :destroy
  has_many :favorite_microposts, through: :favorites, source: :micropost
  
    # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end

  def favorite(micropost)
    favorites.find_or_create_by(micropost_id: micropost.id)
  end

  def unfavorite(micropost)
    favorite = favorites.find_by(micropost_id: micropost.id)
    favorite.destroy if favorite
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update ]
  before_action :correct_user, only: [:edit, :update]
  
  def show
   @user = User.find(params[:id])
   @title = 'Micropost'
   @count = @user.microposts.count
   @microposts = @user.microposts.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを編集しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def followings
    @title = 'あなたがフォローしている方です。'
    @user = User.find(params[:id])
    @users = @user.following_users
    render 'show_follow'
  end

  def followers
    @title = 'あなたのフォロワーです。'
    @user = User.find(params[:id])
    @users = @user.follower_users
    render 'show_follow'
  end
  
  def favorites
    @user = User.find(params[:id])
    @title = 'あなたのお気に入りのポストです。'
    @count = @user.favorite_microposts.count
    @microposts = @user.favorite_microposts.page(params[:page]).per(10)
    render 'show'
  end
    
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :age, :region, :profile)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path if @user != current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>

  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
            
            <%= f.label :name  %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
          
            <%= f.label :age %>
            <%= f.text_field :age %>

            <%= f.label :region %>
            <%= f.text_field :region %>
            
            <%= f.label :profile %>
            <%= f.text_area :profile %>
      
            
            <%= f.submit "保存",data: {confirm: "保存してもよいですか？", disable_with: "処理中" }, class: "btn btn-large btn-primary"  %>
        <% end %>
    </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li><%= user.name %></li>

app/views/users/edit.html.erb
<h1>プロフィールの編集</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
      <h1><%= gravatar_for @user %>
      <%= @user.name %></h1><br>
    <section class="user_info">
      email： <%= @user.email %><br>
      年齢：　<%= @user.age %><br>
      地域：　<%= @user.region %><br>
      プロフィール<br>
      <%= @user.profile %><br>
      <%= link_to "プロフィールを編集する", edit_user_path %><br>
      <%= link_to "your followers", followers_user_path(@user) %><br>
      <%= link_to "your followings", followings_user_path(@user) %><br>
      <%= link_to "your favorit posts", favorites_user_path(@user) %><br>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= @title %> (<%= @count %>)</h3>
      <%= page_entries_info @microposts %>
      <ol class="microposts"><%= render @microposts %></ol>
    <% end %>
    <%= paginate @microposts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <div class="col-md-4">
    <h1><%= gravatar_for @user %>
    <%= @user.name %></h1><br>
  </div>
  <div class="col-md-8">
   <section>
      <h3><%= @title %></h3>
      <h2>  
        <table class="table">
          <thead>
            <tr>
              <th>名前</th>
              <th>地域</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.region %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </h2>
    </section>
  </div>
</div>