config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :microposts do
    member do
      post :retweet
    end
  end
  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  has_many :favorites, foreign_key: 'micropost_id', dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  def favorite?(user)
    favorite_users.include?(user)
  end
  mount_uploader :image, ImageUploader

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  #mount_uploader :image, ImageUploader
    
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  def retweet
    original_micropost = Micropost.find(params[:id])
    if original_micropost
      new_micropost = current_user.microposts.build(content: original_micropost.content, 
                                                   user_id: original_micropost.user_id, original_name: "from" + original_micropost.user.name)
      if new_micropost.save
        redirect_to user_path(current_user)
        flash[:success] = "Retweet Successful"
      else
        redirect_to user_path(current_user), notice: new_micropost.errors.full_messages
      end
    else
      redirect_back_or current_user
      flash[:error] = "Retweet error!"
    end
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content, :original_name, :image, :image_cache, :remove_image)
  end
end

app/views/microposts/_favorite.html.erb
<%= link_to "お気に入りへ。", micropost_favorites_path(micropost),
                        method: :post, remote: true %>

app/views/microposts/_favorite_form.html.erb
<span id="favorite_form-<%= micropost.id %>">
  <% if micropost.favorite?(current_user) %>
    <%= render 'microposts/unfavorite', micropost: micropost %>
  <% else %>
    <%= render 'microposts/favorite', micropost: micropost %>
  <% end %>
</span>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="original_name"><%= micropost.original_name %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "削除", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
    <%= link_to "リツイートする。", retweet_micropost_path(micropost), method: :post %>
    <%= render 'microposts/favorite_form', micropost: micropost %>
    <div class="thumbnail">
      <%= image_tag micropost.image.url %>
    </div>
    <%# end %><br>
  </span>
</li>

app/views/microposts/_retweet_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for(@micropost, remote: true) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">retweet</h4>
      </div>
      <div class="modal-body">
        <div class="field">
        
        </div>
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Retweet", :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/microposts/_unfavorite.html.erb
<%= link_to "お気に入りからはずす。", micropost_favorites_path(micropost),
                          method: :delete, remote: true %>